server:
  port: 8081

spring:
  profiles:
    active: pro



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #hikari
    hikari:
      connection-init-sql: select 1
      minimum-idle: 5
      maximum-pool-size: 50
    #邮箱
  mail:
    host: smtp.qq.com
    username: 1425187931@qq.com
    #SMT授权码
    password: vfsgflogppezhiaj
    port: 25
    protocol: smtp
    default-encoding: UTF-8

mybatis:
  mapper-locations: classpath:com.example.blogapi.mapper/**/*.xml


