logging:
  level:
    com.example.blogapi.mapper: DEBUG

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/springbootmanager?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2b8
    password: 123456