#logging:
#  level:
#    com.example.blogapi.mapper: DEBUG

#spring:
#  datasource:
#    username: root
#    url: jdbc:mysql://localhost:3306/springbootmanager
#    password: 123456

spring:
  datasource:
    username: root
    url: jdbc:mysql://1.12.76.145:3306/springbootmanager?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2b8
    password: Qq1425187931
